### ISSUE TITLE
Afdwingen juiste DigiD authenticatie niveau zodat foutmelding niet meer voorkomt + verbeteren melding

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/irma-issue-app#110]
We kunnen het DigiD authenticatie niveau nu afdwingen. Zorgen dat dit gebeurt zodat gebruikers deze foutmelding niet te zien krijgen.

## Originele issue
Deze tekst is voor een gebruiker niet te begrijpen vrees ik
![image](https://user-images.githubusercontent.com/6553486/222667970-e9f63875-2a75-4510-b1d1-b88bd9c8c111.png)

Het zou kunnen dat Logius hier een standaard goede tekst voor heeft. Een linkje erbij naar wat een inwoner moet doen om wel op het juiste niveau in te loggen lijkt me ook wel gebruiksvriendelijk.

**Comment by marnixdessing** [comment]
Uit de Logius communicatiehandleiding DigiD: 
```
Communiceer niet over het inlogniveau
Binnen uw organisatie wordt wellicht gesproken over betrouwbaarheidsniveaus of inlogniveaus DigiD basis en DigiD midden. Deze termen zeggen uw gebruikers vrij weinig. Spreek in berichtgeving richting gebruikers niet over het verhogen van het inlogniveau. Maak enkel gebruik van de kernboodschappen uit deze handleiding.
```

**Comment by joostvanderborg** [comment]
Als we het niveau nu afdwingen is er geen tekst nodig vanuit ons toch?

**Comment by marnixdessing** [comment]
Ik laat de check + fout afhandeling wel bestaan. Maar een gebruiker zou bij normaal gebruik deze melding niet te zien krijgen inderdaad.
