### ISSUE TITLE
Loggen en inzichtelijk maken van gebruik

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/irma-issue-app#2]
er moet een overzicht komen (in een dashboard, of op een andere manier) waar het volgende te zien is:
- aantal verstrekkingen in de lopende maand
- aantal verstrekkingen in lopende jaar (al dan niet gecatagoriseerd per maand)
- aantal verstrekkingen per gemeente in de afgelopen 24 uur
- aantal verstrekkingen per gemeente in de lopende maand
- aantal verstrekkingen per gemeente in lopende jaar

Deze gegevens worden nu via Splunk verzameld, maar zijn gekoppeld aan de verstrekkingspagina op L7, en verdwijnen dus als die pagina stopt.

dashboard toegankelijk maken voor een specifieke role, bv 'irma-dashboard'.

**Comment by marnixdessing** [comment]
Uitzoeken impact openbaar maken van dashboard (rol met bepaalde rechten), tijd, en informatie die hieruit gehaald kan worden
