### ISSUE TITLE
EPIC: Historische address gegevens uitgeven via IRMA

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/irma-issue-app#30]
## Omschrijving
We hebben besloten gebruikers inzage te geven in hun historische adres gegevens via IRMA. Om dit te implementeren moet zowel de imra-issue-app aangepast worden als de IRMA-BRP api.

## Gerelateerde issues
- [ ] https://github.com/GemeenteNijmegen/devops/issues/137
- [ ] https://github.com/GemeenteNijmegen/devops/issues/138

**Comment by wvdeeckhout** [comment]
@BramWithaar kan deze gesloten worden?

**Comment by wvdeeckhout** [comment]
Deze kan gesloten worden. als de vraag weer komt, dan pakken we het weer op.
